networks:
  agents_backend_network:
    name: agents_backend_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24

volumes:
  # 如果你是 mysql 用户，应将 agents_backend_postgres_data 修改为 agents_backend_mysql_data
  agents_backend_postgres_data:
    name: agents_backend_postgres_data
  agents_backend_redis_data:
    name: agents_backend_redis_data
  agents_backend_static:
    name: agents_backend_static
  agents_backend_static_upload:
    name: agents_backend_static_upload
  agents_backend_rabbitmq_data:
    name: agents_backend_rabbitmq_data

services:
  agents_backend_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: agents_backend_server:latest
    ports:
      - "8001:8001"
    container_name: agents_backend_server
    restart: always
    # 如果你是 mysql 用户，应将 agents_backend_postgres 修改为 agents_backend_mysql
    depends_on:
      - agents_backend_postgres
      - agents_backend_redis
    volumes:
      - ./deploy/backend/docker-compose/.env.server:/agents_backend/backend/.env
      - agents_backend_static:/agents_backend/backend/app/static
      - agents_backend_static_upload:/agents_backend/backend/static/upload
    networks:
      - agents_backend_network
    # 如果你是 mysql 用户，应将 agents_backend_postgres:5432 修改为 agents_backend_mysql:3306
    command:
      - bash
      - -c
      - |
        wait-for-it -s agents_backend_postgres:5432 -s agents_backend_redis:6379 -t 300
        bash /agents_backend/backend/pre_start.sh
        supervisord -c /etc/supervisor/supervisord.conf
        supervisorctl restart

  agents_backend_postgres:
    image: postgres:16
    ports:
      - "${DOCKER_POSTGRES_MAP_PORT:-5432}:5432"
    container_name: agents_backend_postgres
    restart: always
    environment:
      POSTGRES_DB: agents_backend
      POSTGRES_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - agents_backend_postgres_data:/var/lib/postgresql/data
    networks:
      - agents_backend_network

  #  # 如果你是 mysql 用户，应保留 agents_backend_mysql 容器脚本并删除 agents_backend_postgres 容器脚本
  #  agents_backend_mysql:
  #    image: mysql:8.0.41
  #    ports:
  #      - "${DOCKER_MYSQL_MAP_PORT:-3306}:3306"
  #    container_name: agents_backend_mysql
  #    restart: always
  #    environment:
  #      MYSQL_DATABASE: agents_backend
  #      MYSQL_ROOT_PASSWORD: 123456
  #      TZ: Asia/Shanghai
  #    volumes:
  #      - agents_backend_mysql_data:/var/lib/mysql
  #    networks:
  #      - agents_backend_network
  #    command:
  #      --default-authentication-plugin=mysql_native_password
  #      --character-set-server=utf8mb4
  #      --collation-server=utf8mb4_general_ci
  #      --lower_case_table_names=1

  agents_backend_redis:
    image: redis
    ports:
      - "${DOCKER_REDIS_MAP_PORT:-6379}:6379"
    container_name: agents_backend_redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - agents_backend_redis_data:/data
    networks:
      - agents_backend_network

  # 【后端专用】
  # 如果使用此容器，意味着你只需部署后端 API 服务，不需要前端
  # 这与下面的 agents_backend_ui 容器冲突，如果你选择使用 agents_backend_ui 容器，你应该注释或删除 agents_backend_nginx 容器脚本
  agents_backend_nginx:
    image: nginx
    ports:
      - "8000:80"
    container_name: agents_backend_nginx
    restart: always
    depends_on:
      - agents_backend_server
    volumes:
      - ./deploy/backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - agents_backend_static:/www/agents_backend_server/backend/static
      - agents_backend_static_upload:/www/agents_backend_server/backend/static/upload
    networks:
      - agents_backend_network

  #  # 如果服务器内存小于 4GB，CPU 小于四个内核
  #  # 建议通过前端工程单独构建此容器或在本地进行构建
  #  agents_backend_ui:
  #    build:
  #      context: /root/fastapi_best_architecture_ui
  #      dockerfile: Dockerfile
  #    image: agents_backend_ui:latest
  #    ports:
  #      - "80:80"
  #      - "443:443"
  #    container_name: agents_backend_ui
  #    restart: always
  #    depends_on:
  #      - agents_backend_server
  #    command:
  #      - nginx
  #      - -g
  #      - daemon off;
  #    volumes:
  #      # nginx https conf
  #      # 通过 docker 进行部署时，需要打开此配置项并确保<挂载到容器内的证书文件路径>配置
  #      # 与 nginx conf 中的 ssl 证书文件路径配置一致，如果你直接将 ssl 证书文件 cp
  #      # 到了 docker 容器内，则无需挂载证书文件，直接将它们注释或删除即可
  #      # local_ssl_pem_path：你在服务器存放 ssl pem 证书文件的路径，自行修改
  #      # local_ssl_key_path: 你在服务器存放 ssl key 证书文件的路径，自行修改
  #      # /etc/ssl/xxx.pem：挂载到容器内 ssl pem 证书文件的路径，自行修改
  #      # /etc/ssl/xxx.key：挂载到容器内 ssl key 证书文件的路径，自行修改
  #      - local_ssl_pem_path:/etc/ssl/xxx.pem
  #      - local_ssl_key_path:/etc/ssl/xxx.key
  #      - agents_backend_static:/www/agents_backend_server/backend/static
  #      - agents_backend_static_upload:/www/agents_backend_server/backend/static/upload
  #    networks:
  #      - agents_backend_network

  agents_backend_rabbitmq:
    hostname: agents_backend_rabbitmq
    image: rabbitmq:3.13.7
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: agents_backend_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - agents_backend_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - agents_backend_network

  agents_backend_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_TYPE=agents_backend_celery_worker
    image: agents_backend_celery_worker:latest
    # 如果你需要分布式部署 Worker，则必须移除此 container_name 配置
    container_name: agents_backend_celery_worker
    restart: always
    depends_on:
      - agents_backend_rabbitmq
    volumes:
      - ./deploy/backend/docker-compose/.env.server:/agents_backend/backend/.env
    networks:
      - agents_backend_network
    command:
      - bash
      - -c
      - |
        wait-for-it -s agents_backend_rabbitmq:5672 -t 300
        supervisord -c /etc/supervisor/supervisord.conf
        supervisorctl restart

  agents_backend_celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_TYPE=agents_backend_celery_beat
    image: agents_backend_celery_beat:latest
    container_name: agents_backend_celery_beat
    restart: always
    depends_on:
      - agents_backend_rabbitmq
      - agents_backend_celery_worker
    volumes:
      - ./deploy/backend/docker-compose/.env.server:/agents_backend/backend/.env
    networks:
      - agents_backend_network
    command:
      - bash
      - -c
      - |
        wait-for-it -s agents_backend_rabbitmq:5672 -t 300
        supervisord -c /etc/supervisor/supervisord.conf
        supervisorctl restart

  agents_backend_celery_flower:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_TYPE=agents_backend_celery_flower
    image: agents_backend_celery_flower:latest
    ports:
      - "8555:8555"
    container_name: agents_backend_celery_flower
    restart: always
    depends_on:
      - agents_backend_rabbitmq
      - agents_backend_celery_worker
    volumes:
      - ./deploy/backend/docker-compose/.env.server:/agents_backend/backend/.env
    networks:
      - agents_backend_network
    command:
      - bash
      - -c
      - |
        wait-for-it -s agents_backend_rabbitmq:5672 -t 300
        supervisord -c /etc/supervisor/supervisord.conf
        supervisorctl restart
