# This is a config for E2B sandbox template.
# You can use template ID (vg6mdf4wgu5qoijamwb5) or template name (agents-sandbox) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("agents-sandbox") # Sync sandbox
# sandbox = await AsyncSandbox.create("agents-sandbox") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('agents-sandbox')

team_id = "aa3fc779-c133-42ae-97a3-e8e534bfd0f3"
dockerfile = "e2b.Dockerfile"
template_name = "agents-sandbox"
template_id = "vg6mdf4wgu5qoijamwb5"
